name: flutter_bluetooth_serial_example
version: 0.4.0
homepage: https://github.com/edufolly/flutter_bluetooth_serial/tree/master/example/

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  scoped_model:
  cupertino_icons: ^1.0.3
  animated_stack: ^0.2.0
  google_fonts:
  flutter_native_splash:
  flutter_bluetooth_serial:
  speech_to_text: ^6.1.1 
  avatar_glow:
  flutter_tts: ^3.6.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  # flutter_bluetooth_serial:
  #   path: ../
  # integration_test:
  #   sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
